[features]
seeds = false
skip-lint = false

[programs.localnet]
gembots_betting = "ENAhq5nKQnQzjwj48bjUBefu8QvZ9vwArotgfWsbSax6"

[programs.devnet]
gembots_betting = "ENAhq5nKQnQzjwj48bjUBefu8QvZ9vwArotgfWsbSax6"

[programs.mainnet]
gembots_betting = "ENAhq5nKQnQzjwj48bjUBefu8QvZ9vwArotgfWsbSax6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
